maximum:
  name: 50
  content: 140
  description: 1000
  address: 255
  email: 255
  phone: 20
per_user: 10
per_category: 5
per_order: 5
per_product: 8
counter_default: 1
minimum:
  pass: 6
sessions:
  is_remember: "1"
top_order: 5
admin_user_perpage: 10
size:
  product_detail: "500x400"
category_roof: 0
product_recent: 8
product_perpage: 12
per_page: 5
tax_percent: 10
order:
  pending: 0
  accepted: 1
  rejected: 2
admin_product_perpage: 10
data_name: 0
data_price: 1
data_quantity: 2
data_description: 3
data_number_of_order: 5
data_category_id: 6
number_order: 0
